
import javax.swing.JOptionPane;
import java.sql.*;
import project.Select;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rahat
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        iconnotvisible.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtlogusername = new javax.swing.JTextField();
        txtlogpass = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_signup = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        iconvisible = new javax.swing.JLabel();
        iconnotvisible = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Log In");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 640, 75, 24));

        txtlogusername.setText("Username");
        getContentPane().add(txtlogusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 682, 250, 30));

        txtlogpass.setText("password");
        txtlogpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlogpassActionPerformed(evt);
            }
        });
        getContentPane().add(txtlogpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 730, 250, 30));

        btn_login.setText("Log in");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 780, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Dont have an account on trip Bangladesh??");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 800, -1, 30));

        btn_signup.setText("Sign up");
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });
        getContentPane().add(btn_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 830, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Go Sign up and create an accout now");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 830, -1, -1));

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 780, -1, -1));

        jButton2.setText("Forgot password");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 780, -1, -1));

        iconvisible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/visible3.png"))); // NOI18N
        iconvisible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconvisibleMousePressed(evt);
            }
        });
        getContentPane().add(iconvisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 740, -1, -1));

        iconnotvisible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notvisible3.png"))); // NOI18N
        iconnotvisible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconnotvisibleMousePressed(evt);
            }
        });
        getContentPane().add(iconnotvisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 740, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login page.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtlogpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlogpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlogpassActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        String username=txtlogusername.getText();
        String password=txtlogpass.getText();
        if(username.equals("")||password.equals("")){
            JOptionPane.showMessageDialog(null,"Every field is Required");
        }else if(username.equals("admin")||password.equals("0987")){
            setVisible(false);
            new adminpage().setVisible(true);
        }else{
            ResultSet rs=Select.getData("select *from tbl_reg where username='"+username+"' and password='"+password+"'");
            try{
                if(rs.next()){
                    setVisible(false);
                    new homepage().setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Username or password did not match out database");
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Signup().setVisible(true);
    }//GEN-LAST:event_btn_signupActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtlogusername.setText("");
        txtlogpass.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void iconvisibleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconvisibleMousePressed
        // TODO add your handling code here:
        iconvisible.setVisible(false);
        iconnotvisible.setVisible(true);
        txtlogpass.setEchoChar((char)0);
    }//GEN-LAST:event_iconvisibleMousePressed

    private void iconnotvisibleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconnotvisibleMousePressed
        // TODO add your handling code here:
        iconnotvisible.setVisible(false);
        iconvisible.setVisible(true);
        txtlogpass.setEchoChar('*');
    }//GEN-LAST:event_iconnotvisibleMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_signup;
    private javax.swing.JLabel iconnotvisible;
    private javax.swing.JLabel iconvisible;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtlogpass;
    private javax.swing.JTextField txtlogusername;
    // End of variables declaration//GEN-END:variables
}
